
CREATE OR REPLACE
  TYPE man_t UNDER base_t
  ( name  VARCHAR2(30)
  , genus VARCHAR2(30) 
  , CONSTRUCTOR FUNCTION man_t
  ( name  VARCHAR2 
  , genus VARCHAR2 ) RETURN SELF AS RESULT
  , OVERRIDING MEMBER FUNCTION get_name RETURN VARCHAR2
  , MEMBER PROCEDURE set_name 
  ( name VARCHAR2 )
  , MEMBER FUNCTION get_genus RETURN VARCHAR2
  , MEMBER PROCEDURE set_genus 
  ( genus VARCHAR2 ) 
  , OVERRIDING MEMBER FUNCTION to_string RETURN VARCHAR2 )  
  INSTANTIABLE NOT FINAL;
/

show errors

QUIT;
